#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
# autospec version: v12
# autospec commit: fbcebd0
#
Name     : libbpf
Version  : 1.4.3
Release  : 23
URL      : https://github.com/libbpf/libbpf/archive/v1.4.3/libbpf-1.4.3.tar.gz
Source0  : https://github.com/libbpf/libbpf/archive/v1.4.3/libbpf-1.4.3.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause GPL-2.0 LGPL-2.1
Requires: libbpf-lib = %{version}-%{release}
Requires: libbpf-license = %{version}-%{release}
BuildRequires : elfutils-dev
BuildRequires : pkgconfig(libelf)
BuildRequires : pkgconfig(zlib)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
<picture>
<source media="(prefers-color-scheme: dark)" srcset="assets/libbpf-logo-sideways-darkbg.png" width="40%">
<img src="assets/libbpf-logo-sideways.png" width="40%">
</picture>

%package dev
Summary: dev components for the libbpf package.
Group: Development
Requires: libbpf-lib = %{version}-%{release}
Provides: libbpf-devel = %{version}-%{release}
Requires: libbpf = %{version}-%{release}

%description dev
dev components for the libbpf package.


%package lib
Summary: lib components for the libbpf package.
Group: Libraries
Requires: libbpf-license = %{version}-%{release}

%description lib
lib components for the libbpf package.


%package license
Summary: license components for the libbpf package.
Group: Default

%description license
license components for the libbpf package.


%prep
%setup -q -n libbpf-1.4.3
cd %{_builddir}/libbpf-1.4.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1717508833
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
pushd src
export GOAMD64=v2
make  %{?_smp_mflags}
popd


%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1717508833
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libbpf
cp %{_builddir}/libbpf-%{version}/LICENSE.BSD-2-Clause %{buildroot}/usr/share/package-licenses/libbpf/419ec3c0b11c7d22472ea99c03c347413a4ea406 || :
cp %{_builddir}/libbpf-%{version}/LICENSE.LGPL-2.1 %{buildroot}/usr/share/package-licenses/libbpf/91c66db733cf0ff2b3216ec4223b940daf6b26d4 || :
export GOAMD64=v2
pushd src
GOAMD64=v2
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/bpf/bpf.h
/usr/include/bpf/bpf_core_read.h
/usr/include/bpf/bpf_endian.h
/usr/include/bpf/bpf_helper_defs.h
/usr/include/bpf/bpf_helpers.h
/usr/include/bpf/bpf_tracing.h
/usr/include/bpf/btf.h
/usr/include/bpf/libbpf.h
/usr/include/bpf/libbpf_common.h
/usr/include/bpf/libbpf_legacy.h
/usr/include/bpf/libbpf_version.h
/usr/include/bpf/skel_internal.h
/usr/include/bpf/usdt.bpf.h
/usr/lib64/libbpf.so
/usr/lib64/pkgconfig/libbpf.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libbpf.so.1
/usr/lib64/libbpf.so.1.4.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libbpf/419ec3c0b11c7d22472ea99c03c347413a4ea406
/usr/share/package-licenses/libbpf/91c66db733cf0ff2b3216ec4223b940daf6b26d4
